# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import opcua_pb2 as opcua__pb2


class OpcuaServiceStub(object):
    """Definindo o serviço OpcuaService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Notify = channel.unary_unary(
                '/opcua.OpcuaService/Notify',
                request_serializer=opcua__pb2.OpcuaMessage.SerializeToString,
                response_deserializer=opcua__pb2.EmptyMessage.FromString,
                )


class OpcuaServiceServicer(object):
    """Definindo o serviço OpcuaService
    """

    def Notify(self, request, context):
        """Definindo o método Notify, que recebe uma OpcuaMessage e retorna uma EmptyMessage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpcuaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Notify': grpc.unary_unary_rpc_method_handler(
                    servicer.Notify,
                    request_deserializer=opcua__pb2.OpcuaMessage.FromString,
                    response_serializer=opcua__pb2.EmptyMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'opcua.OpcuaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OpcuaService(object):
    """Definindo o serviço OpcuaService
    """

    @staticmethod
    def Notify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/opcua.OpcuaService/Notify',
            opcua__pb2.OpcuaMessage.SerializeToString,
            opcua__pb2.EmptyMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
